### ISSUE TITLE
Trouble with socket->receive

### ISSUE THREAD

**Issue by DJuego** [Lichtso/netLink#20]
More problems with the same code (i have isolated the problems from my super-project. :-D):

[[LINK](https://paste.ofcode.org/36EeRTEU5SHKaxSDicFWY2P) to pastecode]

I feel the code is so big but at least it's complete and it can be run.

I am working in Windows 10 x64 with Visual Studio 2015.

I have two computers in a LAN. The Sender and The Receiver. I am broadcasting UDP packets from the Sender. ~~However i want The Sender can listen too.~~
a) Yes. The Receiver receive a packet!  However socket->receive return 0 bytes!
b) The "workaround" is socket->sgetn... but i suspect it is not the ideal solution...

I have tried to isolate the problem.  I think the bug could be in std::streamsize Socket::showmanyc(). (return zero unexpectedly). 

Curiously when the code is debugged(breakpoints) std::streamsize Socket::showmanyc().  works well sometimes.
  
```cpp
#include <iostream>
#include <chrono>
#include <string>
#include <netLink/netLink.h>

char data[128];

void wait(int milliseconds)
{

	std::chrono::high_resolution_clock::time_point end, start;
	std::chrono::milliseconds ms;

	start = std::chrono::high_resolution_clock::now();
	do
	{
		end = std::chrono::high_resolution_clock::now();
		ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
	} while (ms.count() < milliseconds);
}


int main(int argc, char** argv) {
	//#ifdef WINVER
	netLink::init();
	//#endif

	netLink::SocketManager socketManager;
	std::shared_ptr<netLink::Socket> socket = socketManager.newSocket();
	try
	{
		socket->initAsUdpPeer("0.0.0.0", 3015);
	}
	catch (netLink::Exception exc)
	{
		std::cout << "Address is already in use" << std::endl;
		return 1;
	}
	socket->setBlockingMode(false);



	if (argc > 1)
	{
		std::cout << "The Receiver" << std::endl;
		socketManager.onReceiveRaw = [](netLink::SocketManager *manager, std::shared_ptr< netLink::Socket > socket)
		{

			std::cout << "Receiving..." << std::endl;			
			std::size_t size = socket->receive(data, 128); //THIS LINE DOES NOT WORK!
			if (size > 0)
			{
				std::cout << "Incoming data: " << data << std::endl;
			}
			else
			{
				std::cout << "NO DATA???" << std::endl;
			}

		};

		while (true)
			socketManager.listen(5.0);

	}
	else
	{
		std::cout << "The Sender" << std::endl;
	
		socket->setBroadcast(true);
		socket->hostRemote = "255.255.255.255";
		socket->portRemote = socket->portLocal;	

		char* data = "My data\0";


		while (true)
		{

			wait(1000);
     		        std::cout << "Sending..." << std::endl;
			std::streamsize size = socket->send(data, 128);


		}

	}
	return 0;
}
```
DJuego

**Comment by Lichtso** [comment]
Ok, I see I should probably document this better.
Because there seems to be a lot of confusion around receive, sgetn, showmanyc and so on.

The idea is to only use receive directly if you have disabled the stream buffering by setting NETLINK_DEFAULT_INPUT_BUFFER_SIZE to 0. The same goes with sending and NETLINK_DEFAULT_OUTPUT_BUFFER_SIZE. This has the advantage of knowing the sender of every single packet in UDP.

Else if you don't need such fine grain info about the packets and want to use stream buffering then use the basic_iostream methods in_avail() and sgetn() (or the stream operators << and >>).

If you mix both up the following happens (in UDP):
1. SocketManager receives the packet and writes it in the stream-buffer.
2. Now it informs you by calling the callback socketManager.onReceiveRaw .
3. You try to receive it again and get nothing because the operating system has already given the packet to your application. But it is in the stream-buffer and you are missing it.

Additionally, there is a difference between showmanyc and in_avail.
1. showmanyc() tells you how much is left in the operating systems buffer, you should only use this when not using the stream buffering. Because else the SocketManager handles this for you.
2. in_avail() tells you how much is available to read in both buffers in total, this is therefore the better option in most situations.

**Comment by DJuego** [comment]
Extremely valuable information! Thank you @Lichtso.

Yes. Please update the information with this. Perhaps a new  wiki page too? :-)

DJuego

**Comment by Lichtso** [comment]
Good idea: [new Wiki entry](https://github.com/Lichtso/netLink/wiki/Raw-modes:-Stream-buffering-vs.-direct)
