### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by d223chen** [Lichtso/netLink#27]
I am using Visual Studio 2017 with Microsoft Visual C++ (MSVC++) compiler.

How do I build and create the libraries for this repo?

Right now all I have is the headers and source code. I have tried loading the headers and source code into a project and building with the /DLL option. The compiler tells me "entry point must be defined".

**Comment by d223chen** [comment]
I was able to resolve this by creating a **Static Library Project** and building the project with all the source files and headers in it.

**Comment by Lichtso** [comment]
> The compiler tells me "entry point must be defined".

Sounds like the compiler thinks it should compile an executable instead of a dynamic / shared library. Thus, it expects a main() function and won't find it.


This repo contains a cmake file which should be able to handle all of that for you.
If you don't want to use cmake you have to do it manually:

1. Create a dynamic / shared library project and load the code in it
2. Compile it and install the results + headers globally
3. Link it to your other projects or use something like:
`#pragma comment(lib, "netLink")`
https://msdn.microsoft.com/en-us/library/7f0aews7.aspx
