### ISSUE TITLE
Understanding Serialization sample code

### ISSUE THREAD

**Issue by d223chen** [Lichtso/netLink#28]
I am trying to understand your code sample in the README:

`         
                   
           MsgPack::Serializer serializer(socket);

           serializer << MsgPack__Factory(ArrayHeader(3)); //Next 3 elements belong in this array
           serializer << MsgPack::Factory(true);
           serializer << MsgPack__Factory(ArrayHeader(0));
           serializer << MsgPack::Factory("Hello World!");`

So I am trying my own example: 

`

        netLink::SocketManager socketManager;
        std::shared_ptr<netLink::Socket> socket = socketManager.newMsgPackSocket();

	MsgPack::Serializer serializer(socket.get());

	for (auto const & x : namesStringVector) {
		serializer << MsgPack::Factory(x);
	}

	MsgPack::Deserializer deserializer(socket.get());

	deserializer.deserialize([](std::unique_ptr<MsgPack::Element> parsed) {
		std::cout << "Parsed: " << *parsed << "\n";
		return false;
	}, true);

	`

But I get no output. I suspect my choice of object "socket" for your example is incorrect. I cannot find the information in the TCP/UDP sample code so I thought I'd ask here.

What is the correct initialization and object creation of "socket" in your example? My use case would be more for writing to a local variable rather than actually passing a message using TCP/UDP.

**Comment by Lichtso** [comment]
Sockets are bidirectional, meaning it is intended that you won't receive what you just sent.

What do you want to achieve?
Sending something through the network or writing it locally to a file?

If you want to send something through the network, then copy the examples of TCP / UDP respectively. The important lines are:
`std::shared_ptr<netLink::Socket> socket = socketManager.newMsgPackSocket();` and
`netLink::MsgPackSocket& msgPackSocket = *static_cast<netLink::MsgPackSocket*>(socket.get());`
The `netLink::SocketManager` is useful for automatic events.

If you want to use MsgPack locally, then just use `MsgPack::Serializer` and `MsgPack::Deserializer` directly without sockets. Their constructor accepts everything that is a [std::streambuf*](http://www.cplusplus.com/reference/streambuf/streambuf/).

I hope this helps, otherwise you need to explain more about your application.
